spring.application.name=cloud-run-api

server.port=${PORT:8080}

# Configuracion del Bucket de GCP suministrado en el reto
gcp.bucket.name=linko-challenge-files
gcp.bucket.prefix=${GCP_BUCKET_PREFIX:}

# Produccion Listo: Exponer health check de Actuator en /health
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health

# Resuelve la colision de configuracion entre Spring Boot y GCP Storage
spring.main.allow-bean-definition-overriding=true