steps:
  # 1. Compilar y construir la imagen usando el repositorio de Artifact Registry asignado
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/linko-training/linko-java-repo/$_SERVICE_NAME:$SHORT_SHA',
      './cloud-run-api'
    ]

  # 2. Subir la imagen empaquetada al repositorio compartido
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/linko-training/linko-java-repo/$_SERVICE_NAME:$SHORT_SHA'
    ]

  # 3. Desplegar de forma automática a Cloud Run con Gobernanza y límites de producción
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=us-central1-docker.pkg.dev/linko-training/linko-java-repo/$_SERVICE_NAME:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=reto1-runtime@linko-training.iam.gserviceaccount.com'
      # Inyectamos el prefijo como variable de entorno para que Spring Boot lo lea en la nube
      - '--set-env-vars=GCP_BUCKET_PREFIX=$_BUCKET_PREFIX'
      # Configuración "Production-Ready" exigida para la nota máxima (9-10/10)
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=3'
      - '--concurrency=80'

  # 🔑 4. GENERAR ID TOKEN CON LOS PERMISOS DEL PIPELINE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "===================================================="
        echo "SOLICITANDO TOKEN FIRMADO DESDE EL PIPELINE DE FORMA DIRECTA..."
        echo "===================================================="

        # 1. Extraemos el token interno del build agent
        BUILD_TOKEN=$$(gcloud auth print-access-token)

        # 2. Le pedimos a la API de Google un ID Token firmado a nombre de reto1-runtime
        ID_TOKEN=$$(curl -s -X POST "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/reto1-runtime@linko-training.iam.gserviceaccount.com:generateIdToken" \
          -H "Authorization: Bearer $$BUILD_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"audience\": \"https://linko-java-api-sr-430799291004.us-central1.run.app\", \"includeEmail\": true}" | jq -r '.token')

        echo "TU ENDPOINT RESPONDIENDO CON EL TOKEN CORRECTO:"
        echo ""
        # 3. Aquí hacemos el curl real simulando al evaluador
        curl -i -H "Authorization: Bearer $$ID_TOKEN" https://linko-java-api-sr-430799291004.us-central1.run.app/health
        echo ""
        echo "===================================================="

images:
  - 'us-central1-docker.pkg.dev/linko-training/linko-java-repo/$_SERVICE_NAME:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY